version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    image: agontcharov/budget-tracker
    ports:
      - "80:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
